### ISSUE TITLE
babel-runtime dependency error

### ISSUE THREAD

**Issue by kristianmandrup** [aam229/inquirer-path#1]
Trying to use it, I get:

```
$ babel-node index.js
module.js:474
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristianmandrup/repos/generators/master-inquisitor/node_modules/inquirer-path/lib/PathPrompt.js:3:13)
```

When I look at the file `node_modules/inquirer-path/lib/PathPrompt.js`
Indeed, I don't have `babel-runtime` in my project. I think your compilation surely should output ES5 files that are not reliant on babel runtime.

``` js
'use strict';

var _keys = require('babel-runtime/core-js/object/keys');

var _keys2 = _interopRequireDefault(_keys);

var _assign = require('babel-runtime/core-js/object/assign');

var _assign2 = _interopRequireDefault(_assign);

var _getPrototypeOf = require('babel-runtime/core-js/object/get-prototype-of');

var _getPrototypeOf2 = _interopRequireDefault(_getPrototypeOf);

var _classCallCheck2 = require('babel-runtime/helpers/classCallCheck');
```

**Comment by aam229** [comment]
Sorry I did not take care of this earlier. It is fixed with the beta version.

**Comment by Fuzzyma** [comment]
I have the same problem with beta3 so I would like to reopen this issue.
I really would like to use this piece of awesomeness

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (Z:\heat\arduino\testbed\node_modules\inquirer-path\lib\PathPrompt.js:3:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by aam229** [comment]
I got rid of the babel transform-runtime plugin altogether. Thank you for pointing out the issue.
